/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.usermodule.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.usermodule.model.Useraction;

import com.usermodule.service.UseractionLocalService;
import com.usermodule.service.UseractionService;
import com.usermodule.service.persistence.UseractionPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the useraction local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.usermodule.service.impl.UseractionLocalServiceImpl}.
 * </p>
 *
 * @author admin
 * @see com.usermodule.service.impl.UseractionLocalServiceImpl
 * @see com.usermodule.service.UseractionLocalServiceUtil
 * @generated
 */
public abstract class UseractionLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements UseractionLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.usermodule.service.UseractionLocalServiceUtil} to access the useraction local service.
	 */

	/**
	 * Adds the useraction to the database. Also notifies the appropriate model listeners.
	 *
	 * @param useraction the useraction
	 * @return the useraction that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Useraction addUseraction(Useraction useraction)
		throws SystemException {
		useraction.setNew(true);

		return useractionPersistence.update(useraction, false);
	}

	/**
	 * Creates a new useraction with the primary key. Does not add the useraction to the database.
	 *
	 * @param userActionId the primary key for the new useraction
	 * @return the new useraction
	 */
	public Useraction createUseraction(long userActionId) {
		return useractionPersistence.create(userActionId);
	}

	/**
	 * Deletes the useraction with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userActionId the primary key of the useraction
	 * @return the useraction that was removed
	 * @throws PortalException if a useraction with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Useraction deleteUseraction(long userActionId)
		throws PortalException, SystemException {
		return useractionPersistence.remove(userActionId);
	}

	/**
	 * Deletes the useraction from the database. Also notifies the appropriate model listeners.
	 *
	 * @param useraction the useraction
	 * @return the useraction that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Useraction deleteUseraction(Useraction useraction)
		throws SystemException {
		return useractionPersistence.remove(useraction);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Useraction.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return useractionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return useractionPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return useractionPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return useractionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Useraction fetchUseraction(long userActionId)
		throws SystemException {
		return useractionPersistence.fetchByPrimaryKey(userActionId);
	}

	/**
	 * Returns the useraction with the primary key.
	 *
	 * @param userActionId the primary key of the useraction
	 * @return the useraction
	 * @throws PortalException if a useraction with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Useraction getUseraction(long userActionId)
		throws PortalException, SystemException {
		return useractionPersistence.findByPrimaryKey(userActionId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return useractionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the useractions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of useractions
	 * @param end the upper bound of the range of useractions (not inclusive)
	 * @return the range of useractions
	 * @throws SystemException if a system exception occurred
	 */
	public List<Useraction> getUseractions(int start, int end)
		throws SystemException {
		return useractionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of useractions.
	 *
	 * @return the number of useractions
	 * @throws SystemException if a system exception occurred
	 */
	public int getUseractionsCount() throws SystemException {
		return useractionPersistence.countAll();
	}

	/**
	 * Updates the useraction in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param useraction the useraction
	 * @return the useraction that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Useraction updateUseraction(Useraction useraction)
		throws SystemException {
		return updateUseraction(useraction, true);
	}

	/**
	 * Updates the useraction in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param useraction the useraction
	 * @param merge whether to merge the useraction with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the useraction that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Useraction updateUseraction(Useraction useraction, boolean merge)
		throws SystemException {
		useraction.setNew(false);

		return useractionPersistence.update(useraction, merge);
	}

	/**
	 * Returns the useraction local service.
	 *
	 * @return the useraction local service
	 */
	public UseractionLocalService getUseractionLocalService() {
		return useractionLocalService;
	}

	/**
	 * Sets the useraction local service.
	 *
	 * @param useractionLocalService the useraction local service
	 */
	public void setUseractionLocalService(
		UseractionLocalService useractionLocalService) {
		this.useractionLocalService = useractionLocalService;
	}

	/**
	 * Returns the useraction remote service.
	 *
	 * @return the useraction remote service
	 */
	public UseractionService getUseractionService() {
		return useractionService;
	}

	/**
	 * Sets the useraction remote service.
	 *
	 * @param useractionService the useraction remote service
	 */
	public void setUseractionService(UseractionService useractionService) {
		this.useractionService = useractionService;
	}

	/**
	 * Returns the useraction persistence.
	 *
	 * @return the useraction persistence
	 */
	public UseractionPersistence getUseractionPersistence() {
		return useractionPersistence;
	}

	/**
	 * Sets the useraction persistence.
	 *
	 * @param useractionPersistence the useraction persistence
	 */
	public void setUseractionPersistence(
		UseractionPersistence useractionPersistence) {
		this.useractionPersistence = useractionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.usermodule.model.Useraction",
			useractionLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.usermodule.model.Useraction");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return Useraction.class;
	}

	protected String getModelClassName() {
		return Useraction.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = useractionPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = UseractionLocalService.class)
	protected UseractionLocalService useractionLocalService;
	@BeanReference(type = UseractionService.class)
	protected UseractionService useractionService;
	@BeanReference(type = UseractionPersistence.class)
	protected UseractionPersistence useractionPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private UseractionLocalServiceClpInvoker _clpInvoker = new UseractionLocalServiceClpInvoker();
}