/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.usermodule.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Useraction service. Represents a row in the &quot;usermodule_Useraction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.usermodule.model.impl.UseractionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.usermodule.model.impl.UseractionImpl}.
 * </p>
 *
 * @author admin
 * @see Useraction
 * @see com.usermodule.model.impl.UseractionImpl
 * @see com.usermodule.model.impl.UseractionModelImpl
 * @generated
 */
public interface UseractionModel extends AuditedModel, BaseModel<Useraction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a useraction model instance should use the {@link Useraction} interface instead.
	 */

	/**
	 * Returns the primary key of this useraction.
	 *
	 * @return the primary key of this useraction
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this useraction.
	 *
	 * @param primaryKey the primary key of this useraction
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user action ID of this useraction.
	 *
	 * @return the user action ID of this useraction
	 */
	public long getUserActionId();

	/**
	 * Sets the user action ID of this useraction.
	 *
	 * @param userActionId the user action ID of this useraction
	 */
	public void setUserActionId(long userActionId);

	/**
	 * Returns the company ID of this useraction.
	 *
	 * @return the company ID of this useraction
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this useraction.
	 *
	 * @param companyId the company ID of this useraction
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this useraction.
	 *
	 * @return the user ID of this useraction
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this useraction.
	 *
	 * @param userId the user ID of this useraction
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this useraction.
	 *
	 * @return the user uuid of this useraction
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this useraction.
	 *
	 * @param userUuid the user uuid of this useraction
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this useraction.
	 *
	 * @return the user name of this useraction
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this useraction.
	 *
	 * @param userName the user name of this useraction
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this useraction.
	 *
	 * @return the create date of this useraction
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this useraction.
	 *
	 * @param createDate the create date of this useraction
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this useraction.
	 *
	 * @return the modified date of this useraction
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this useraction.
	 *
	 * @param modifiedDate the modified date of this useraction
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the userclickaction of this useraction.
	 *
	 * @return the userclickaction of this useraction
	 */
	@AutoEscape
	public String getUserclickaction();

	/**
	 * Sets the userclickaction of this useraction.
	 *
	 * @param userclickaction the userclickaction of this useraction
	 */
	public void setUserclickaction(String userclickaction);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Useraction useraction);

	public int hashCode();

	public CacheModel<Useraction> toCacheModel();

	public Useraction toEscapedModel();

	public String toString();

	public String toXmlString();
}